package com.AFG.persistance;
//Generated 26 avr. 2018 14:26:27 by Hibernate Tools 5.1.0.Alpha1

/**
* User generated by hbm2java
*/

public class Demande implements java.io.Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int reference;
	private User demandeur;
	private Outillage outillage;
	private String nature;
	private int qte;
	private int state;
	private String date;
	private String ch; // Cahier de charge
	private String notes;
	
	@Override
	public String toString() {
		return "Demande [reference=" + reference + ", demandeur=" + demandeur + ", outillage=" + outillage + ", nature="
				+ nature + ", qte=" + qte + ", state=" + state + ", date=" + date + ", ch=" + ch + ", notes=" + notes
				+ "]";
	}

	public int getReference() {
		return reference;
	}

	public void setReference(int reference) {
		this.reference = reference;
	}

	public User getDemandeur() {
		return demandeur;
	}

	public void setDemandeur(User demandeur) {
		this.demandeur = demandeur;
	}

	public Outillage getOutillage() {
		return outillage;
	}

	public void setOutillage(Outillage outillage) {
		this.outillage = outillage;
	}

	public String getNature() {
		return nature;
	}

	public void setNature(String nature) {
		this.nature = nature;
	}

	public int getQte() {
		return qte;
	}

	public void setQte(int qte) {
		this.qte = qte;
	}

	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getCh() {
		return ch;
	}

	public void setCh(String ch) {
		this.ch = ch;
	}

	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ch == null) ? 0 : ch.hashCode());
		result = prime * result + ((date == null) ? 0 : date.hashCode());
		result = prime * result + ((demandeur == null) ? 0 : demandeur.hashCode());
		result = prime * result + ((nature == null) ? 0 : nature.hashCode());
		result = prime * result + ((notes == null) ? 0 : notes.hashCode());
		result = prime * result + ((outillage == null) ? 0 : outillage.hashCode());
		result = prime * result + qte;
		result = prime * result + reference;
		result = prime * result + state;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Demande other = (Demande) obj;
		if (ch == null) {
			if (other.ch != null)
				return false;
		} else if (!ch.equals(other.ch))
			return false;
		if (date == null) {
			if (other.date != null)
				return false;
		} else if (!date.equals(other.date))
			return false;
		if (demandeur == null) {
			if (other.demandeur != null)
				return false;
		} else if (!demandeur.equals(other.demandeur))
			return false;
		if (nature == null) {
			if (other.nature != null)
				return false;
		} else if (!nature.equals(other.nature))
			return false;
		if (notes == null) {
			if (other.notes != null)
				return false;
		} else if (!notes.equals(other.notes))
			return false;
		if (outillage == null) {
			if (other.outillage != null)
				return false;
		} else if (!outillage.equals(other.outillage))
			return false;
		if (qte != other.qte)
			return false;
		if (reference != other.reference)
			return false;
		if (state != other.state)
			return false;
		return true;
	}

}
