package com.AFG.persistance;
// Generated 28 mai 2018 08:48:25 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.List;

/**
 * Outillage generated by hbm2java
 */
public class Outillage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer reference;
	private Fournisseur fournisseur;
	private String code;
	private String description;
	private String client;
	private Date dateVal;
	private Integer agile;
	private int frequence;
	private String empl;
	private List<Affectation>affectations ;
	private List<Demande>demandes;
	private Integer nb;


	public Outillage() {
	}

	public Outillage(Fournisseur fournisseur, String code, int frequence) {
		this.fournisseur = fournisseur;
		this.code = code;
		this.frequence = frequence;
	}

	public Outillage(Fournisseur fournisseur, String code, String description, String client, Integer nb, Date dateVal,
			Integer agile, int frequence, String empl, List<Affectation> affectations, List<Demande> demandes) {
		this.fournisseur = fournisseur;
		this.code = code;
		this.description = description;
		this.client = client;
		this.nb = nb;
		this.dateVal = dateVal;
		this.agile = agile;
		this.frequence = frequence;
		this.empl = empl;
		this.affectations = affectations;
		this.demandes = demandes;
	}

	public Integer getReference() {
		return this.reference;
	}

	public void setReference(Integer reference) {
		this.reference = reference;
	}

	public Fournisseur getFournisseur() {
		return this.fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	public Integer getNb() {
		return this.nb;
	}

	public void setNb(Integer qte) {
		this.nb = qte;
	}

	public Date getDateVal() {
		return this.dateVal;
	}

	public void setDateVal(Date dateVal) {
		this.dateVal = dateVal;
	}

	public Integer getAgile() {
		return this.agile;
	}

	public void setAgile(Integer agile) {
		this.agile = agile;
	}

	public int getFrequence() {
		return this.frequence;
	}

	public void setFrequence(int frequence) {
		this.frequence = frequence;
	}

	public String getEmpl() {
		return this.empl;
	}

	public void setEmpl(String empl) {
		this.empl = empl;
	}

	public List<Affectation> getAffectations() {
		return this.affectations;
	}

	public void setAffectations(List<Affectation> affectations) {
		this.affectations = affectations;
	}

	public List<Demande> getDemandes() {
		return this.demandes;
	}

	public void setDemandes(List<Demande> demandes) {
		this.demandes = demandes;
	}
	
	@Override
	public String toString() {
		return "Outillage [reference=" + reference + ", fournisseur=" + fournisseur + ", code=" + code
				+ ", description=" + description + ", client=" + client + ", qte=" + nb + ", dateVal=" + dateVal
				+ ", agile=" + agile + ", frequence=" + frequence + ", empl=" + empl + ", affectations=" + affectations
				+ ", demandes=" + demandes + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((affectations == null) ? 0 : affectations.hashCode());
		result = prime * result + ((agile == null) ? 0 : agile.hashCode());
		result = prime * result + ((client == null) ? 0 : client.hashCode());
		result = prime * result + ((code == null) ? 0 : code.hashCode());
		result = prime * result + ((dateVal == null) ? 0 : dateVal.hashCode());
		result = prime * result + ((demandes == null) ? 0 : demandes.hashCode());
		result = prime * result + ((description == null) ? 0 : description.hashCode());
		result = prime * result + ((empl == null) ? 0 : empl.hashCode());
		result = prime * result + ((fournisseur == null) ? 0 : fournisseur.hashCode());
		result = prime * result + frequence;
		result = prime * result + ((nb == null) ? 0 : nb.hashCode());
		result = prime * result + ((reference == null) ? 0 : reference.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Outillage other = (Outillage) obj;
		if (affectations == null) {
			if (other.affectations != null)
				return false;
		} else if (!affectations.equals(other.affectations))
			return false;
		if (agile == null) {
			if (other.agile != null)
				return false;
		} else if (!agile.equals(other.agile))
			return false;
		if (client == null) {
			if (other.client != null)
				return false;
		} else if (!client.equals(other.client))
			return false;
		if (code == null) {
			if (other.code != null)
				return false;
		} else if (!code.equals(other.code))
			return false;
		if (dateVal == null) {
			if (other.dateVal != null)
				return false;
		} else if (!dateVal.equals(other.dateVal))
			return false;
		if (demandes == null) {
			if (other.demandes != null)
				return false;
		} else if (!demandes.equals(other.demandes))
			return false;
		if (description == null) {
			if (other.description != null)
				return false;
		} else if (!description.equals(other.description))
			return false;
		if (empl == null) {
			if (other.empl != null)
				return false;
		} else if (!empl.equals(other.empl))
			return false;
		if (fournisseur == null) {
			if (other.fournisseur != null)
				return false;
		} else if (!fournisseur.equals(other.fournisseur))
			return false;
		if (frequence != other.frequence)
			return false;
		if (nb == null) {
			if (other.nb != null)
				return false;
		} else if (!nb.equals(other.nb))
			return false;
		if (reference == null) {
			if (other.reference != null)
				return false;
		} else if (!reference.equals(other.reference))
			return false;
		return true;
	}

}
