package com.AFG.bean;


import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;


//Generated 26 avr. 2018 14:26:27 by Hibernate Tools 5.1.0.Alpha1

/**
* User generated by hbm2java
*/

@ManagedBean(name = "navigationRulesBean")
@SessionScoped
public class NavigationRulesBean {
	
	public String utilisateurs(){
		return "utilisateurs";
	}
	
	public String home(){
		return "home";
	}
	
	public String produits(){
		return "produits";
	}
	
	public String fournisseurs(){
		return "fournisseurs";
	}
	
	public String outillages(){
		return "outillages";
	}
	
	public String acceuil(){
		return "acceuil";
	}
	
	public String demandes(){
		return "demandes";
	}
	
	public String maintenance(){
		return "maintenance";
	}
}